import { shallow } from 'enzyme';
import React from 'react'
import ErrorBoundry from './ErrorBoundry';

it('displays error message on error generated by child', () => {

  function ProblemChild() {
    throw new Error('Error thrown from problem child');
    return <div>Error</div>; // eslint-disable-line
  }

  const wrapper = shallow(
    <ErrorBoundry>
      <ProblemChild />
    </ErrorBoundry>);
  const error = new Error('hi!');
  wrapper.find('ProblemChild').simulateError(error);
  expect(wrapper.state('hasError')).toEqual(true);
})